apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ni7wg7k13-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ni7wg7k13-go 
  name: ni7wg7k13-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ni7wg7k13-go 
